/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sipetor.view;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import net.sf.jasperreports.engine.JRException;
import sipetor.reports.GenerateReport;

/**
 *
 * @author Aldy
 */
public class FormMainMenu extends javax.swing.JFrame {
    
    /**
     * Creates new form FormMainMenu
     */
    public FormMainMenu() {
        initComponents();
        
    }

    FormMainMenu(String nama_karyawan) {
       initComponents();
       jLabel1.setText(nama_karyawan);
    }

    

   

      

  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnQuit = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnGolongan = new javax.swing.JMenuItem();
        mnKaryawan = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mnSparepart = new javax.swing.JMenuItem();
        mnPelanggan = new javax.swing.JMenuItem();
        mnTransaksi = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        mnTransaksi1 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        jLabel2.setText("Username : ");
        jToolBar1.add(jLabel2);

        jLabel1.setText("Guest");
        jToolBar1.add(jLabel1);

        mnQuit.setText("File");

        jMenuItem1.setText("Quit");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        mnQuit.add(jMenuItem1);

        jMenuBar1.add(mnQuit);

        jMenu2.setText("Admin");

        mnGolongan.setText("Golongan");
        mnGolongan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnGolonganActionPerformed(evt);
            }
        });
        jMenu2.add(mnGolongan);

        mnKaryawan.setText("Karyawan");
        mnKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnKaryawanActionPerformed(evt);
            }
        });
        jMenu2.add(mnKaryawan);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Master Data");

        mnSparepart.setText("Sparepart");
        mnSparepart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnSparepartActionPerformed(evt);
            }
        });
        jMenu3.add(mnSparepart);

        mnPelanggan.setText("Pelanggan");
        mnPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnPelangganActionPerformed(evt);
            }
        });
        jMenu3.add(mnPelanggan);

        jMenuBar1.add(jMenu3);

        mnTransaksi.setText("Transaksi");
        mnTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnTransaksiActionPerformed(evt);
            }
        });

        jMenuItem2.setText("Service Motor");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        mnTransaksi.add(jMenuItem2);

        jMenuBar1.add(mnTransaksi);

        mnTransaksi1.setText("Report");
        mnTransaksi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnTransaksi1ActionPerformed(evt);
            }
        });

        jMenuItem3.setText("Transaksi");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        mnTransaksi1.add(jMenuItem3);

        jMenuItem4.setText("Slip Gaji");
        mnTransaksi1.add(jMenuItem4);

        jMenuBar1.add(mnTransaksi1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(248, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(245, Short.MAX_VALUE)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnSparepartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnSparepartActionPerformed
        // TODO add your handling code here:
        new FormMasterSparepart(this, rootPaneCheckingEnabled).show();
    }//GEN-LAST:event_mnSparepartActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void mnGolonganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnGolonganActionPerformed
        // TODO add your handling code here:
        new FormMasterGolongann(this, rootPaneCheckingEnabled).show();
                
    }//GEN-LAST:event_mnGolonganActionPerformed

    private void mnKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnKaryawanActionPerformed
        // TODO add your handling code here:
        new FormMasterKaryawan(this, rootPaneCheckingEnabled).show();
    }//GEN-LAST:event_mnKaryawanActionPerformed

    private void mnPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnPelangganActionPerformed
        new FormMasterPelanggan(this, rootPaneCheckingEnabled).show();
    }//GEN-LAST:event_mnPelangganActionPerformed

    private void mnTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnTransaksiActionPerformed
       
    }//GEN-LAST:event_mnTransaksiActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
       new FormTransaksi().setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        GenerateReport report = new GenerateReport();
            report.GenerateReportTransaksi();// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void mnTransaksi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnTransaksi1ActionPerformed
        GenerateReport report = new GenerateReport();
            report.GenerateReportTransaksi();
   
                 
    }//GEN-LAST:event_mnTransaksi1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMasterGolongann.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMasterGolongann.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMasterGolongann.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMasterGolongann.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMainMenu ().setVisible(true);             
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuItem mnGolongan;
    private javax.swing.JMenuItem mnKaryawan;
    private javax.swing.JMenuItem mnPelanggan;
    private javax.swing.JMenu mnQuit;
    private javax.swing.JMenuItem mnSparepart;
    private javax.swing.JMenu mnTransaksi;
    private javax.swing.JMenu mnTransaksi1;
    // End of variables declaration//GEN-END:variables
}
